export const PANEL_COVERAGE_FILES = [
  'src/App.tsx',
  'src/components/common/ConfirmationModal.tsx',
  'src/components/common/NotificationContainer.tsx',
  'src/components/common/PageTransition.tsx',
  'src/components/common/PageTransitionLayer.ts',
  'src/components/common/SecondaryScreenShell.tsx',
  'src/components/common/SplashScreen.tsx',
  'src/components/layout/MainLayout.tsx',
  'src/components/workspace/SectionPanel.tsx',
  'src/components/workspace/WorkspacePage.tsx',
  'src/features/budgets/validation.ts',
  'src/features/dashboard/useDashboardSnapshot.ts',
  'src/features/diagnostics/credentials.ts',
  'src/features/operations/useOperationsFeed.ts',
  'src/pages/AiProvidersNativeKeyEditPage.tsx',
  'src/pages/BudgetsPage.tsx',
  'src/pages/ChangesPage.tsx',
  'src/pages/DashboardPage.tsx',
  'src/pages/DiagnosticsPage.tsx',
  'src/pages/LoginPage.tsx',
  'src/pages/OnboardingPage.tsx',
  'src/pages/OperationsPage.tsx',
  'src/shared/ui/index.tsx',
] as const;
